### ISSUE TITLE
http://v8dox.com/: Lots of misdirected and broken links

### ISSUE THREAD

**Issue by ackalker** [v8-dox/v8-dox.github.io#1]
Visiting http://v8dox.com/ , I find that the top three links for the node.js v0.12.x docs point to docs for (older) io.js versions. Also, selecting any of the items in the drop-down list after "View an older relase" results in a 404.

Examples:

Top link [node.js v0.12.7](http://v8dox.com/b949437/html/index.html) points to docs for io.js v1.0.3.
Top link [node.js v0.12.6](http://v8dox.com/9d3288c/html/index.html) points to docs for io.js v1.0.2 - v1.0.0
Top link [node.js v0.12.5](http://v8dox.com/78b0e30/html/index.html) points to docs for node.js v0.12.7

Similar confusion happens for the top links under node.js v0.10.x and io.js. Only the link to docs for [io.js v3.0.0](http://v8dox.com/3d3c687/html/index.html) appears to be correct.

**Comment by chad3814** [comment]
crap, thanks for pointing it out. it's just he index.html that is wrong, and I edited that by hand (badly I guess). I'll try to push a fix for the links today, and am working on rewriting the script in javascript instead of bash to get it into better shape.

**Comment by chad3814** [comment]
okay so I fixed the index.html, they all point to the right place now, but the titles in the dox are wrong. I wil regenerate the dox (and fix the script) to get those right.

**Comment by chad3814** [comment]
I'm much happier with the generation now, thanks for the kick @ackalker

**Comment by ackalker** [comment]
You're welcome :)
